// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	Joystick* driveJoystick;
	Joystick* targetJoystick;
	
	JoystickButton* targetButton;
	
	JoystickButton* changeShooter;
	JoystickButton* gearShift;
	JoystickButton* flipFrisbees;
	JoystickButton* nudgeFrisbees;
	JoystickButton* climbDown;
	JoystickButton* climbUp;
	JoystickButton* decreasePitch;
	JoystickButton* increasePitch;
	JoystickButton* shootPiston;
	JoystickButton* htarget;
	JoystickButton* vtarget;
	JoystickButton* resetGyro;
	JoystickButton* turnLeft;
	JoystickButton* turnRight;
	JoystickButton* increaseShootSpeed;
	JoystickButton* decreaseShootSpeed;
	
	JoystickButton* pidDrive;
	JoystickButton* changeAngle;
public:
	OI();

	Joystick* getDriveJoystick();
	Joystick* getTargetJoystick();
	float GetX();
	float GetY();
};
#endif
