// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "Commands.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* driveTrainSpeedControlLeft1;
	static SpeedController* driveTrainSpeedControlLeft2;
	static SpeedController* driveTrainSpeedControlRight1;
	static SpeedController* driveTrainSpeedControlRight2;
	static Encoder* driveTrainLeftEncoder;
	static Encoder* driveTrainRightEncoder;
	static RobotDrive* driveTrainRobotDrive3663;
	static Solenoid* driveTrainGearShift1;
	static Solenoid* driveTrainGearShift2;
	static SpeedController* shooterShooterMotorControl;
	static Encoder* shooterShooterEncoder;
	static Solenoid* diskManagementShootSolenoid1;
	static Solenoid* diskManagementShootSolenoid2;
	static Solenoid* diskManagementflipperSolenoid1;
	static Solenoid* diskManagementFlipperSolenoid2;
	static Gyro* driveTrainGyro;
	static SpeedController* pitchPitchMotor;
	static DigitalInput* pitchLimitSwitchMax;
	static DigitalInput* pitchLimitSwitchMin;
	static Relay* pneumaticsCompressorSwitch;
	static DigitalInput* pneumaticsCompressorLimitSwitch;
	static DigitalInput* photoelectricGroundSensor;
	static DigitalInput* photoelectricShooterSensor;
	static SpeedController* climberClimbMotorController;
	static DigitalInput* climberUpperLimitSwitch;
	static DigitalInput* climberLowerLimitSwitch;
	static Relay* lightsledRelay;
	static AnalogChannel* rangeFinderFrontUltrasonicSensor;
	static AnalogChannel* rangeFinderBackUltrasonicSensor;
	static AnalogChannel* rangeFinderLeftUltrasonicSensor;
	static AnalogChannel* rangeFinderRightUltrasonicSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
