// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVETOLINECOMMAND_H
#define DRIVETOLINECOMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveToLineCommand: public Command {
private:
	float driveSpeed;
	float maxSpeed;
	float curve;
	float driveProgress;
	float decayFactor;
	bool  reachedEndpoint;
	float driveDistance;
public:
	DriveToLineCommand(float distanceToDrive);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
