// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShootPistonCommand.h"

#define WAIT_PERIOD 2.0

ShootPistonCommand::ShootPistonCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Robot::diskManagement->RetractShootPiston();
	SetTimeout(WAIT_PERIOD);
}
// Called just before this Command runs the first time
void ShootPistonCommand::Initialize() {
	Robot::diskManagement->ExtendShootPiston();
	Wait(0.5);
	Robot::diskManagement->RetractShootPiston();
}
// Called repeatedly when this Command is scheduled to run
void ShootPistonCommand::Execute() {

}
// Make this return true when this Command no longer needs to run execute()
bool ShootPistonCommand::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void ShootPistonCommand::End() {

}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShootPistonCommand::Interrupted() {
	Robot::diskManagement->RetractShootPiston();
}
