// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef DISKMANAGEMENT_H
#define DISKMANAGEMENT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class DiskManagement: public Subsystem {
private:
	void SetShootPiston(bool extendPiston);
	void SetFlipperPiston(bool extendPiston);
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid* shootSolenoid1;
	Solenoid* shootSolenoid2;
	Solenoid* flipperSolenoid1;
	Solenoid* flipperSolenoid2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DiskManagement();
	void InitDefaultCommand();
	void ExtendShootPiston();
	void RetractShootPiston();
	void ExtendFlipperPiston();
	void RetractFlipperPiston();
};
#endif
