// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef PHOTOELECTRIC_H
#define PHOTOELECTRIC_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "AnalogChannel.h"
/*
 * @author ExampleAuthor
 */
class Photoelectric: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DigitalInput* groundSensor;
	DigitalInput* shooterSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Photoelectric();
	void InitDefaultCommand();
	unsigned int GetGroundStatus();
	unsigned int GetShooterStatus();
	void UpdateStatus();
};
#endif
