// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef PITCH_H
#define PITCH_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Pitch: public Subsystem {
private:
	void SetPitch(bool isIncreasing, float seconds);
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* pitchMotor;
	DigitalInput* limitSwitchMax;
	DigitalInput* limitSwitchMin;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Pitch();
	void InitDefaultCommand();
	void IncreasePitch(float seconds = 0.1);
	void DecreasePitch(float seconds = 0.1);
	void SetMaxPitch();
	void SetMinPitch();
	void UpdateStatus();
};
#endif
