// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Pneumatics.h"
#include "../Robotmap.h"
Pneumatics::Pneumatics() : Subsystem("Pneumatics") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	compressorSwitch = RobotMap::pneumaticsCompressorSwitch;
	compressorLimitSwitch = RobotMap::pneumaticsCompressorLimitSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	compressorSwitch->Set(Relay::kReverse);
}
    
void Pneumatics::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new CheckCompressorSwitch());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Pneumatics::TurnOff(){
	compressorSwitch->Set(Relay::kOff);
}
void Pneumatics::TurnOn(){
	compressorSwitch->Set(Relay::kReverse);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
