// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RangeFinder.h"
#include "../Robotmap.h"
#include "math.h"
RangeFinder::RangeFinder() : Subsystem("RangeFinder") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frontUltrasonicSensor = RobotMap::rangeFinderFrontUltrasonicSensor;
	backUltrasonicSensor = RobotMap::rangeFinderBackUltrasonicSensor;
	leftUltrasonicSensor = RobotMap::rangeFinderLeftUltrasonicSensor;
	rightUltrasonicSensor = RobotMap::rangeFinderRightUltrasonicSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void RangeFinder::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
double* RangeFinder::GetDistance(){
	Distances[0] = floor(frontUltrasonicSensor->GetVoltage() / 0.0098);
	Distances[1] = floor(backUltrasonicSensor->GetVoltage() / 0.0098);
	Distances[2] = floor(leftUltrasonicSensor->GetVoltage() / 0.0098);
	Distances[3] = floor(rightUltrasonicSensor->GetVoltage() / 0.0098);
	
	return Distances;
}
void RangeFinder::UpdateStatus(){
	SmartDashboard::PutNumber("Ultrasonic Front Range:", RangeFinder::GetDistance()[0]);
	SmartDashboard::PutNumber("Ultrasonic Back Range:", RangeFinder::GetDistance()[1]);
	SmartDashboard::PutNumber("Ultrasonic Left Range:", RangeFinder::GetDistance()[2]);
	SmartDashboard::PutNumber("Ultrasonic Right Range:", RangeFinder::GetDistance()[3]);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
